- name: Restart NX server
  service:
    name: nxserver
    state: restarted
- name: Restart lightdm
  service:
    name: lightdm
    state: restarted
- name: Restart Mumble server
  service:
    name: mumble-server
    state: restarted
- name: Restart NGINX server
  service:
    name: nginx
    state: restarted
- name: reload docker-compose
  command: "sh -c 'cd /etc/docker-compose && docker-compose up -d'"
